included:
  - FullscreenSwitcher
  - FullscreenSwitcherDemo
disabled_rules:
  - unused_closure_parameter
  - trailing_comma
opt_in_rules:
  - empty_count
  - private_outlet
  - force_unwrapping
  - conditional_returns_on_newline

legacy_nsgeometry_functions: error
trailing_newline: error
opening_brace: error
empty_count: error
comma: error
colon: error
force_cast: error
type_name:
  min_length:
    error: 3
  max_length:
    error: 40
private_outlet: error
trailing_semicolon: error
force_try: error
force_unwrapping: error
mark: error
function_body_length:
  warning: 80
  error: 80
operator_whitespace: error
control_statement: error
legacy_constant: error
line_length:
  warning: 140
  error: 140
return_arrow_whitespace: error
closing_brace: error
conditional_returns_on_newline: error
statement_position:
  statement_mode: default
  severity: error
trailing_whitespace:
  severity: error
  ignores_empty_lines: false
type_body_length:
  error: 250
legacy_constructor: error
cyclomatic_complexity:
  error: 10
file_length:
  error: 500
leading_whitespace: error
legacy_cggeometry_functions: error
variable_name:
  min_length:
    warning: 3
  max_length:
    error: 40
closure_end_indentation: error
closure_parameter_position: error
closure_spacing: error
empty_parentheses_with_trailing_closure: error
function_parameter_count:
  warning: 5
  error: 8
implicit_getter: error
large_tuple:
  warning: 3
  error: 4
object_literal: error
operator_usage_whitespace: error
overridden_super_call: error
prohibited_super_call: error
redundant_string_enum_value: error
redundant_void_return: error
shorthand_operator: error
switch_case_on_newline: error
syntactic_sugar: error
void_return: error
weak_delegate: error
# missing_docs
explicit_init: error
todo: warning
